title: My docs
description: An awesome docs project
permalink: pretty
search_enabled: true
color_scheme: dark
baseurl:     "/continuous-integration-travis-demo"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
